### ISSUE TITLE
flac2mp3 ignores destination path on Windows 10

### ISSUE THREAD

**Issue by FrankEBailey** [bamthomas/flac2mp3#2]
if my FLACs are in g:\Albums and I want to transcode them to my a: drive in the /mp3 folder, I use the following syntax according to the --help function:

g:\albums\> flac2mp3.py g:\albums a:\mp3

One of two things happens. Either the destination appears to be ignored outright, and the mp3 transcodes just go to the same folders the flacs are in, or they go to the root of a: drive, ignoring the /mp3 folder.

Knowing me it's probably just me doing something wrong or idiotic, but if you could provide a concrete example of how to type the paths etc on Windows that would be a huge help. Thanks!

**Comment by bamthomas** [comment]
Thanks for your interest.
quick answer (not tested) I'd try to write : 

    g:\albums> flac2mp3.py g:\albums\*  a:\mp3\

At least I'm (sill !) using it like this (on linux) : normally the script reads a list so if you put g:\albums it is just the directory. Then the first n-1 items are the input paths and the last one is the target path.

If it doesn't work, maybe it is related to how python reads arguments on windows.
