### ISSUE TITLE
Does this already skip already existing...

### ISSUE THREAD

**Issue by bonelifer** [bamthomas/flac2mp3#5]
Does this skip already existing albums, instead of over-writing them?

**Comment by bamthomas** [comment]
We can't just look at the file existing on the disk as it could have been transcoded but with other tags. So if the file is present and the tags are the same (and the equality is not that easy to do so sometimes it fails), then it is skipped.

see 
https://github.com/bamthomas/flac2mp3/blob/12403df322d3205452a087bf09179ad847d6fbe1/flac2mp3/__init__.py#L191
